# Generated by Django 6.0.4 on 2026-04-16 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_escalationrule_ticketcategory_ticket_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending', 'Pending – Awaiting User'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('item', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('edit_note', models.CharField(blank=True, max_length=255)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
    ]
