# Generated by Codex for Zynaros v2.
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [('tickets', '0006_profile_role_ticket_external_message_id')]
    operations = [
        migrations.CreateModel(name='ServiceCatalogItem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=160, unique=True)), ('slug', models.SlugField(max_length=80, unique=True)), ('request_type', models.CharField(choices=[('incident', 'Incident'), ('service_request', 'Service Request'), ('access_request', 'Access Request'), ('onboarding', 'Onboarding'), ('offboarding', 'Offboarding'), ('hardware', 'Hardware Request')], default='service_request', max_length=30)), ('category', models.CharField(choices=[('network', 'Network'), ('access', 'Access / Permissions'), ('hardware', 'Hardware'), ('software', 'Software'), ('email', 'Email'), ('password', 'Password Reset'), ('printer', 'Printer'), ('onboarding', 'Onboarding'), ('other', 'Other')], default='other', max_length=30)), ('description', models.TextField(blank=True)), ('fulfillment_hint', models.CharField(blank=True, max_length=255)), ('default_priority', models.CharField(default='medium', max_length=20)), ('approval_required', models.BooleanField(default=False)), ('estimated_hours', models.IntegerField(default=24)), ('is_active', models.BooleanField(default=True))], options={'ordering': ['name']}),
        migrations.AddField('ticket', 'request_type', models.CharField(choices=[('incident', 'Incident'), ('service_request', 'Service Request'), ('access_request', 'Access Request'), ('onboarding', 'Onboarding'), ('offboarding', 'Offboarding'), ('hardware', 'Hardware Request'), ('problem', 'Problem / Recurring Issue')], default='incident', max_length=30)),
        migrations.AddField('ticket', 'impact', models.CharField(choices=[('single_user', 'Single User'), ('team', 'Team'), ('department', 'Department'), ('company', 'Company')], default='single_user', max_length=30)),
        migrations.AddField('ticket', 'urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
        migrations.AddField('ticket', 'approval_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=20)),
        migrations.AddField('ticket', 'business_service', models.CharField(blank=True, max_length=120)),
        migrations.AddField('ticket', 'catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.servicecatalogitem')),
    ]
